{
  "19_20-2-2-python": {
    "BUQGY7N7.py": {
      "functionality": {
        "passed": 0,
        "total": 13,
        "pass_rate": "0.00%",
        "details": [
          {
            "test": 1,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "1",
            "actual": ""
          },
          {
            "test": 2,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "14",
            "actual": ""
          },
          {
            "test": 3,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "0",
            "actual": ""
          },
          {
            "test": 4,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "3720010",
            "actual": ""
          },
          {
            "test": 5,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 6,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 7,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 8,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "4599\nTrue",
            "actual": ""
          },
          {
            "test": 9,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "18388\nTrue",
            "actual": ""
          },
          {
            "test": 10,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "11951\nTrue",
            "actual": ""
          },
          {
            "test": 11,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 39, in <module>\nNameError: name 'CustomStack' is not defined",
            "expected": "50863132\nTrue",
            "actual": ""
          },
          {
            "test": 12,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 38, in <module>\nNameError: name 'getRandom' is not defined",
            "expected": "3",
            "actual": ""
          },
          {
            "test": 13,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 38, in <module>\nNameError: name 'getRandom' is not defined",
            "expected": "True",
            "actual": ""
          }
        ]
      },
      "quality": {
        "pylint_score": 10.0
      },
      "complexity": {
        "cprofile_total_time": null,
        "cprofile_output_summary": "Profiling Error: name 'CustomStack' is not defined"
      }
    }
  },
  "19_20-5-1-python": {
    "BUQGY7N7.py": {
      "functionality": {
        "passed": 8,
        "total": 11,
        "pass_rate": "72.73%",
        "details": [
          {
            "test": 1,
            "status": "PASS"
          },
          {
            "test": 2,
            "status": "PASS"
          },
          {
            "test": 3,
            "status": "PASS"
          },
          {
            "test": 4,
            "status": "PASS"
          },
          {
            "test": 5,
            "status": "PASS"
          },
          {
            "test": 6,
            "status": "PASS"
          },
          {
            "test": 7,
            "status": "PASS"
          },
          {
            "test": 8,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 35, in <module>\nNameError: name 'random' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 9,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 35, in <module>\nNameError: name 'random' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 10,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 35, in <module>\nNameError: name 'random' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 11,
            "status": "PASS"
          }
        ]
      },
      "quality": {
        "pylint_score": 10.0
      },
      "complexity": {
        "cprofile_total_time": 0.0018404,
        "cprofile_output_summary": "         26 function calls in 0.002 seconds\n\n   Ordered by: cumulative time\n\n   ncalls  tottime  percall  cumtime  percall filename:lineno(function)\n        1    0.001    0.001    0.002    0.002 {built-in method builtins.exec}\n        1    0.000    0.000    0.001    0.001 <string>:1(<module>)\n        1    0.000    0.000    0.000    0.000 {built-in method builtins.print}\n        1    0.000    0.000    0.000    0.000 <string>:1(bfs)\n       12    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}\n        6    0.000    0.000    0.000    0.000 {method 'pop' of 'list' objects}\n        3    0.000    0.000    0.000    0.000 {built-in method builtins.len}\n        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}\n\n\n"
      }
    }
  },
  "20_21-1-2-python": {
    "2V5AQFDC.py": {
      "functionality": {
        "passed": 7,
        "total": 9,
        "pass_rate": "77.78%",
        "details": [
          {
            "test": 3,
            "status": "PASS"
          },
          {
            "test": 4,
            "status": "PASS"
          },
          {
            "test": 5,
            "status": "PASS"
          },
          {
            "test": 6,
            "status": "PASS"
          },
          {
            "test": 7,
            "status": "PASS"
          },
          {
            "test": 8,
            "status": "PASS"
          },
          {
            "test": 9,
            "status": "ERROR",
            "detail": "Execution Error: [WinError 206] The filename or extension is too long"
          },
          {
            "test": 10,
            "status": "PASS"
          },
          {
            "test": 11,
            "status": "ERROR",
            "detail": "Execution Error: [WinError 206] The filename or extension is too long"
          }
        ]
      },
      "quality": {
        "pylint_score": 10.0
      },
      "complexity": {
        "cprofile_total_time": null,
        "cprofile_output_summary": "Profiling Error: name 'solution' is not defined"
      }
    }
  },
  "19_20-3-1-python": {
    "3QDYQU4I.py": {
      "functionality": {
        "passed": 0,
        "total": 11,
        "pass_rate": "0.00%",
        "details": [
          {
            "test": 1,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True\nTrue",
            "actual": ""
          },
          {
            "test": 2,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 3,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 4,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 5,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 6,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 7,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 8,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 9,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 10,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 11,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nNameError: name 'ListToSort' is not defined",
            "expected": "True",
            "actual": ""
          }
        ]
      },
      "quality": {
        "pylint_score": 0.0
      },
      "complexity": {
        "cprofile_total_time": null,
        "cprofile_output_summary": "Profiling Error: name 'ListToSort' is not defined"
      }
    }
  },
  "20_21-3-1-python": {
    "2DXKHJJW.py": {
      "functionality": {
        "passed": 15,
        "total": 20,
        "pass_rate": "75.00%",
        "details": [
          {
            "test": 2,
            "status": "PASS"
          },
          {
            "test": 3,
            "status": "PASS"
          },
          {
            "test": 4,
            "status": "PASS"
          },
          {
            "test": 5,
            "status": "PASS"
          },
          {
            "test": 6,
            "status": "PASS"
          },
          {
            "test": 7,
            "status": "PASS"
          },
          {
            "test": 8,
            "status": "PASS"
          },
          {
            "test": 9,
            "status": "PASS"
          },
          {
            "test": 10,
            "status": "PASS"
          },
          {
            "test": 11,
            "status": "PASS"
          },
          {
            "test": 12,
            "status": "PASS"
          },
          {
            "test": 13,
            "status": "PASS"
          },
          {
            "test": 14,
            "status": "PASS"
          },
          {
            "test": 15,
            "status": "PASS"
          },
          {
            "test": 16,
            "status": "PASS"
          },
          {
            "test": 17,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 23, in <module>\nNameError: name 'random' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 18,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 23, in <module>\nNameError: name 'random' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 19,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 24, in <module>\nNameError: name 'random' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 20,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 24, in <module>\nNameError: name 'random' is not defined",
            "expected": "True",
            "actual": ""
          },
          {
            "test": 21,
            "status": "FAIL",
            "detail": "Runtime Error: Traceback (most recent call last):\n  File \"<string>\", line 24, in <module>\nNameError: name 'random' is not defined",
            "expected": "True",
            "actual": ""
          }
        ]
      },
      "quality": {
        "pylint_score": 10.0
      },
      "complexity": {
        "cprofile_total_time": 0.00042510000000000003,
        "cprofile_output_summary": "         8 function calls in 0.000 seconds\n\n   Ordered by: cumulative time\n\n   ncalls  tottime  percall  cumtime  percall filename:lineno(function)\n        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}\n        1    0.000    0.000    0.000    0.000 <string>:1(<module>)\n        1    0.000    0.000    0.000    0.000 {built-in method builtins.print}\n        1    0.000    0.000    0.000    0.000 <string>:1(knapSack)\n        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}\n        3    0.000    0.000    0.000    0.000 {built-in method builtins.len}\n\n\n"
      }
    }
  },
  "20_21-3-2-python": {
    "2FXPE3DD.py": {
      "functionality": {
        "passed": 9,
        "total": 10,
        "pass_rate": "90.00%",
        "details": [
          {
            "test": 4,
            "status": "PASS"
          },
          {
            "test": 5,
            "status": "PASS"
          },
          {
            "test": 6,
            "status": "PASS"
          },
          {
            "test": 7,
            "status": "PASS"
          },
          {
            "test": 8,
            "status": "PASS"
          },
          {
            "test": 9,
            "status": "PASS"
          },
          {
            "test": 10,
            "status": "PASS"
          },
          {
            "test": 11,
            "status": "PASS"
          },
          {
            "test": 12,
            "status": "PASS"
          },
          {
            "test": 13,
            "status": "ERROR",
            "detail": "Execution Error: [WinError 206] The filename or extension is too long"
          }
        ]
      },
      "quality": {
        "pylint_score": 0.62
      },
      "complexity": {
        "cprofile_total_time": 0.0027932000000000005,
        "cprofile_output_summary": "         989 function calls (947 primitive calls) in 0.003 seconds\n\n   Ordered by: cumulative time\n\n   ncalls  tottime  percall  cumtime  percall filename:lineno(function)\n        1    0.002    0.002    0.003    0.003 {built-in method builtins.exec}\n        1    0.000    0.000    0.001    0.001 <string>:1(<module>)\n        1    0.000    0.000    0.000    0.000 <string>:1(calc)\n     45/3    0.000    0.000    0.000    0.000 <string>:2(DFS)\n        1    0.000    0.000    0.000    0.000 {built-in method builtins.print}\n      447    0.000    0.000    0.000    0.000 {built-in method builtins.max}\n      446    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}\n        1    0.000    0.000    0.000    0.000 <string>:8(<listcomp>)\n       45    0.000    0.000    0.000    0.000 {built-in method builtins.len}\n        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}\n\n\n"
      }
    }
  }
}